import 'package:meta/meta.dart';

@immutable
class Blog {
  /// The id of the blog (this will be a unique ID generated by Firebase).
  final String id;

  ///The id of the author (this will also be generated by Firebase).
  final String authorId;

  /// The title of the blog post.
  final String title;

  /// The subtitle of the blog post.
  final String subtitle;

  /// The content of the blog post (we'll store its content as a single string).
  final String content;

  /// The date and time the blog was originally created.
  final DateTime dateCreated;

  /// The date and time the blog was last updated.
  final DateTime dateUpdated;

  Blog({
    this.id,
    @required this.authorId,
    @required this.title,
    this.subtitle,
    @required this.content,
    this.dateCreated,
    this.dateUpdated,
  })  : assert(authorId != null, 'Author ID must not be null'),
        assert(title != null, 'Title must not be null'),
        assert(content != null, 'Content must not be null');

  /// Creates a copy of a [Blog], updating the fields specified.
  Blog copyWith({
    String authorId,
    String title,
    String subtitle,
    String content,
    DateTime dateCreated,
    DateTime dateUpdated,
  }) {
    return Blog(
      id: id,
      authorId: authorId ?? this.authorId,
      title: title ?? this.title,
      subtitle: subtitle ?? this.subtitle,
      content: content ?? this.content,
      dateCreated: dateCreated ?? this.dateCreated,
      dateUpdated: dateUpdated ?? this.dateUpdated,
    );
  }

  @override
  String toString() {
    return '''
Blog {
  id: $id,
  authorId: $authorId,
  title: $title,
  subtitle: $subtitle,
  content: $content,
  dateCreated: $dateCreated,
  dateUpdated: $dateUpdated,
}  
''';
  }
}
