import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';

part 'blog.g.dart';

@immutable
@JsonSerializable(includeIfNull: false)
class Blog {
  /// The id of the blog (this will be a unique ID generated by Firebase).
  final String id;

  ///The id of the author (this will also be generated by Firebase).
  @JsonKey(nullable: false)
  final String authorId;

  /// The title of the blog post.
  @JsonKey(nullable: false)
  final String title;

  /// The subtitle of the blog post.
  final String subtitle;

  /// The content of the blog post (we'll store its content as a single string).
  @JsonKey(nullable: false)
  final String content;

  /// The topic or category of the blog.
  final String topic;

  /// The URL of the thumbnail image of the blog post.
  final String thumbnail;

  /// The date and time the blog was originally created.
  final DateTime dateCreated;

  /// The date and time the blog was last updated.
  final DateTime dateUpdated;

  const Blog({
    this.id,
    @required this.authorId,
    @required this.title,
    this.subtitle,
    @required this.content,
    this.topic,
    this.thumbnail,
    this.dateCreated,
    this.dateUpdated,
  })  : assert(authorId != null, 'Author ID must not be null'),
        assert(title != null, 'Title must not be null'),
        assert(content != null, 'Content must not be null');

  /// Creates a JSON representation of this [Blog].
  factory Blog.fromJson(Map<String, dynamic> json) => _$BlogFromJson(json);

  /// Creates a [Blog] instance from its JSON representation.
  Map<String, dynamic> toJson() => _$BlogToJson(this);

  /// Creates a copy of a [Blog], updating the fields specified.
  Blog copyWith({
    String authorId,
    String title,
    String subtitle,
    String content,
    DateTime dateCreated,
    DateTime dateUpdated,
  }) {
    return Blog(
      id: id,
      authorId: authorId ?? this.authorId,
      title: title ?? this.title,
      subtitle: subtitle ?? this.subtitle,
      content: content ?? this.content,
      dateCreated: dateCreated ?? this.dateCreated,
      dateUpdated: dateUpdated ?? this.dateUpdated,
    );
  }

  @override
  String toString() {
    return '''
Blog {
  id: $id,
  authorId: $authorId,
  title: $title,
  subtitle: $subtitle,
  content: $content,
  dateCreated: $dateCreated,
  dateUpdated: $dateUpdated,
}  
''';
  }
}
